"""add is_locked to beds

Revision ID: 07959a398336
Revises: c85490249870
Create Date: 2026-03-07 02:22:27.229323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07959a398336'
down_revision: Union[str, None] = 'c85490249870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beds', 'is_locked')
    # ### end Alembic commands ###
