"""add cultivar_name to plants

Revision ID: 2302d3be10ab
Revises: 316dc2641c29
Create Date: 2026-02-28 21:56:08.294050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2302d3be10ab'
down_revision: Union[str, None] = '316dc2641c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add cultivar_name column
    op.add_column('plants', sa.Column('cultivar_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_plants_cultivar_name'), 'plants', ['cultivar_name'], unique=False)

    # 2. Data migration: split duplicate permapeople_plants → plant mappings.
    #    When multiple permapeople_plants entries share one plant_id, keep the
    #    oldest link and create new Plant entries for the rest.
    conn = op.get_bind()
    dupes = conn.execute(sa.text("""
        SELECT plant_id, array_agg(id ORDER BY id) AS pp_ids
        FROM permapeople_plants
        WHERE plant_id IS NOT NULL
        GROUP BY plant_id
        HAVING count(*) > 1
    """)).fetchall()

    for plant_id, pp_ids in dupes:
        # Skip the first entry (keep its link), create new plants for the rest
        for pp_id in pp_ids[1:]:
            pp = conn.execute(sa.text("""
                SELECT common_name, scientific_name, image_url, description
                FROM permapeople_plants WHERE id = :id
            """), {"id": pp_id}).fetchone()

            result = conn.execute(sa.text("""
                INSERT INTO plants (common_name, scientific_name, image_url, description,
                                    source, is_user_defined, data_sources, created_at, updated_at)
                VALUES (:cn, :sn, :img, :desc, 'permapeople', false,
                        ARRAY['permapeople']::varchar[], now(), now())
                RETURNING id
            """), {
                "cn": pp.common_name or "Unknown",
                "sn": pp.scientific_name,
                "img": pp.image_url,
                "desc": pp.description,
            })
            new_plant_id = result.fetchone()[0]

            conn.execute(sa.text("""
                UPDATE permapeople_plants SET plant_id = :new_id WHERE id = :pp_id
            """), {"new_id": new_plant_id, "pp_id": pp_id})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_cultivar_name'), table_name='plants')
    op.drop_column('plants', 'cultivar_name')
    # ### end Alembic commands ###
