"""add user_plant_favorites

Revision ID: 458eba7e6de8
Revises: 2302d3be10ab
Create Date: 2026-03-01 03:07:22.084289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '458eba7e6de8'
down_revision: Union[str, None] = '2302d3be10ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plant_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_plant_favorites')
    # ### end Alembic commands ###
