"""add watering group plantings and schedule relationships

Revision ID: 4bc9d9561a96
Revises: 9aa156e45527
Create Date: 2026-02-25 03:50:58.723280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bc9d9561a96'
down_revision: Union[str, None] = '9aa156e45527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantings', sa.Column('watering_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_plantings_watering_group_id'), 'plantings', ['watering_group_id'], unique=False)
    op.create_foreign_key('plantings_watering_group_id_fkey', 'plantings', 'watering_groups', ['watering_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('watering_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watering_groups', 'updated_at')
    op.drop_constraint(None, 'plantings', type_='foreignkey')
    op.drop_index(op.f('ix_plantings_watering_group_id'), table_name='plantings')
    op.drop_column('plantings', 'watering_group_id')
    # ### end Alembic commands ###
