"""add data_sources to plants

Revision ID: 5955cee52287
Revises: 8136c34c46ff
Create Date: 2026-02-28 00:57:27.646357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5955cee52287'
down_revision: Union[str, None] = '8136c34c46ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('data_sources', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'data_sources')
    # ### end Alembic commands ###
