"""add_planting_grid_fields

Revision ID: 8136c34c46ff
Revises: 1f8b43fa65e8
Create Date: 2026-02-27 03:39:22.658966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8136c34c46ff'
down_revision: Union[str, None] = '1f8b43fa65e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantings', sa.Column('grid_x', sa.Integer(), nullable=True))
    op.add_column('plantings', sa.Column('grid_y', sa.Integer(), nullable=True))
    op.add_column('plantings', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantings', 'is_locked')
    op.drop_column('plantings', 'grid_y')
    op.drop_column('plantings', 'grid_x')
    # ### end Alembic commands ###
