"""phase_b_drop_trefle_add_data_source_runs_expand_permapeople

Revision ID: 8f9370278329
Revises: 91906b6b278b
Create Date: 2026-02-28 04:12:51.870511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f9370278329'
down_revision: Union[str, None] = '91906b6b278b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_species', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('gap_filled', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_runs_source'), 'data_source_runs', ['source'], unique=False)
    op.drop_table('trefle_plants')
    # Data migration: remove "trefle" from enrichment_rules source_priority arrays
    op.execute("""
        UPDATE enrichment_rules
        SET source_priority = array_remove(source_priority, 'trefle')
        WHERE 'trefle' = ANY(source_priority)
    """)
    # For rules that had only trefle, set sensible defaults
    op.execute("""
        UPDATE enrichment_rules
        SET source_priority = '{permapeople}'
        WHERE source_priority = '{}' OR source_priority IS NULL
    """)
    op.add_column('permapeople_plants', sa.Column('height', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('width', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('spacing', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('life_cycle', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('days_to_harvest', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('days_to_maturity', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('soil_ph', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('propagation_method', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('propagation_cuttings', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('propagation_direct_sowing', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('propagation_transplanting', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('germination_time', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('germination_temperature', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('sow_outdoors', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('sow_indoors', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('start_indoors_weeks', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('start_outdoors_weeks', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('plant_transplant', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('plant_cuttings', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('plant_division', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('seed_planting_depth', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('seed_viability', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('seed_weight_per_1000_g', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('nitrogen_fixing', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('nitrogen_usage', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('drought_resistant', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('native_to', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('introduced_into', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('habitat', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('root_type', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('root_depth', sa.String(length=50), nullable=True))
    op.add_column('permapeople_plants', sa.Column('leaves', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('pests', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('diseases', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('pollination', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('medicinal', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('medicinal_parts', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('edible_uses', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('utility', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('warning', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('alternate_name', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('genus', sa.String(length=100), nullable=True))
    op.add_column('permapeople_plants', sa.Column('wikipedia_url', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('pfaf_url', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('powo_url', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('permapeople_plants', sa.Column('slug', sa.String(length=200), nullable=True))
    op.add_column('permapeople_plants', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permapeople_plants', 'version')
    op.drop_column('permapeople_plants', 'slug')
    op.drop_column('permapeople_plants', 'image_url')
    op.drop_column('permapeople_plants', 'powo_url')
    op.drop_column('permapeople_plants', 'pfaf_url')
    op.drop_column('permapeople_plants', 'wikipedia_url')
    op.drop_column('permapeople_plants', 'genus')
    op.drop_column('permapeople_plants', 'alternate_name')
    op.drop_column('permapeople_plants', 'warning')
    op.drop_column('permapeople_plants', 'utility')
    op.drop_column('permapeople_plants', 'edible_uses')
    op.drop_column('permapeople_plants', 'medicinal_parts')
    op.drop_column('permapeople_plants', 'medicinal')
    op.drop_column('permapeople_plants', 'pollination')
    op.drop_column('permapeople_plants', 'diseases')
    op.drop_column('permapeople_plants', 'pests')
    op.drop_column('permapeople_plants', 'leaves')
    op.drop_column('permapeople_plants', 'root_depth')
    op.drop_column('permapeople_plants', 'root_type')
    op.drop_column('permapeople_plants', 'habitat')
    op.drop_column('permapeople_plants', 'introduced_into')
    op.drop_column('permapeople_plants', 'native_to')
    op.drop_column('permapeople_plants', 'drought_resistant')
    op.drop_column('permapeople_plants', 'nitrogen_usage')
    op.drop_column('permapeople_plants', 'nitrogen_fixing')
    op.drop_column('permapeople_plants', 'seed_weight_per_1000_g')
    op.drop_column('permapeople_plants', 'seed_viability')
    op.drop_column('permapeople_plants', 'seed_planting_depth')
    op.drop_column('permapeople_plants', 'plant_division')
    op.drop_column('permapeople_plants', 'plant_cuttings')
    op.drop_column('permapeople_plants', 'plant_transplant')
    op.drop_column('permapeople_plants', 'start_outdoors_weeks')
    op.drop_column('permapeople_plants', 'start_indoors_weeks')
    op.drop_column('permapeople_plants', 'sow_indoors')
    op.drop_column('permapeople_plants', 'sow_outdoors')
    op.drop_column('permapeople_plants', 'germination_temperature')
    op.drop_column('permapeople_plants', 'germination_time')
    op.drop_column('permapeople_plants', 'propagation_transplanting')
    op.drop_column('permapeople_plants', 'propagation_direct_sowing')
    op.drop_column('permapeople_plants', 'propagation_cuttings')
    op.drop_column('permapeople_plants', 'propagation_method')
    op.drop_column('permapeople_plants', 'soil_ph')
    op.drop_column('permapeople_plants', 'days_to_maturity')
    op.drop_column('permapeople_plants', 'days_to_harvest')
    op.drop_column('permapeople_plants', 'life_cycle')
    op.drop_column('permapeople_plants', 'spacing')
    op.drop_column('permapeople_plants', 'width')
    op.drop_column('permapeople_plants', 'height')
    op.create_table('trefle_plants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trefle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scientific_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('common_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('family', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('genus', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('edible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('edible_parts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('light', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soil_humidity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soil_nutriments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soil_salinity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soil_texture', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atmospheric_humidity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ph_minimum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ph_maximum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('minimum_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('minimum_precipitation_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_precipitation_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bloom_months', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('growth_months', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('fruit_months', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('days_to_harvest', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spread_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('row_spacing_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('minimum_root_depth_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('growth_rate', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('average_height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('toxicity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ligneous_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('flower_color', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('foliage_color', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('foliage_texture', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fruit_color', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name='trefle_plants_plant_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='trefle_plants_pkey'),
    sa.UniqueConstraint('trefle_id', name='trefle_plants_trefle_id_key')
    )
    op.drop_index(op.f('ix_data_source_runs_source'), table_name='data_source_runs')
    op.drop_table('data_source_runs')
    # ### end Alembic commands ###
