"""add source tables and enrichment rules

Revision ID: 91906b6b278b
Revises: 5955cee52287
Create Date: 2026-02-28 01:21:19.161653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91906b6b278b'
down_revision: Union[str, None] = '5955cee52287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.Enum('priority', 'union', 'longest', 'average', name='enrichment_strategy_enum'), nullable=False),
    sa.Column('source_priority', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('perenual_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perenual_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perenual_id')
    )
    op.create_table('permapeople_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permapeople_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('water_requirement', sa.String(length=100), nullable=True),
    sa.Column('light_requirement', sa.String(length=100), nullable=True),
    sa.Column('hardiness_zone', sa.String(length=20), nullable=True),
    sa.Column('growth', sa.String(length=100), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('edible', sa.String(length=100), nullable=True),
    sa.Column('edible_parts', sa.String(length=200), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permapeople_id')
    )
    op.create_table('trefle_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trefle_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('edible', sa.Boolean(), nullable=True),
    sa.Column('edible_parts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('light', sa.Integer(), nullable=True),
    sa.Column('soil_humidity', sa.Integer(), nullable=True),
    sa.Column('soil_nutriments', sa.Integer(), nullable=True),
    sa.Column('soil_salinity', sa.Integer(), nullable=True),
    sa.Column('soil_texture', sa.Integer(), nullable=True),
    sa.Column('atmospheric_humidity', sa.Integer(), nullable=True),
    sa.Column('ph_minimum', sa.Float(), nullable=True),
    sa.Column('ph_maximum', sa.Float(), nullable=True),
    sa.Column('minimum_temperature_c', sa.Float(), nullable=True),
    sa.Column('maximum_temperature_c', sa.Float(), nullable=True),
    sa.Column('minimum_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('maximum_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('bloom_months', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('growth_months', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fruit_months', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('spread_cm', sa.Float(), nullable=True),
    sa.Column('row_spacing_cm', sa.Float(), nullable=True),
    sa.Column('minimum_root_depth_cm', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('average_height_cm', sa.Float(), nullable=True),
    sa.Column('maximum_height_cm', sa.Float(), nullable=True),
    sa.Column('toxicity', sa.String(length=100), nullable=True),
    sa.Column('ligneous_type', sa.String(length=50), nullable=True),
    sa.Column('flower_color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('foliage_color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('foliage_texture', sa.String(length=50), nullable=True),
    sa.Column('fruit_color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trefle_id')
    )
    # ### end Alembic commands ###

    # ── Seed enrichment rules (raw SQL to avoid asyncpg enum cast issue) ─────
    op.execute(
        """
        INSERT INTO enrichment_rules (field_name, strategy, source_priority, updated_at) VALUES
        ('common_name', 'priority', '{perenual,trefle,permapeople}', NOW()),
        ('scientific_name', 'priority', '{trefle,perenual,permapeople}', NOW()),
        ('image_url', 'priority', '{perenual,trefle}', NOW()),
        ('plant_type', 'priority', '{trefle,permapeople}', NOW()),
        ('water_needs', 'priority', '{trefle,permapeople}', NOW()),
        ('sun_requirement', 'priority', '{trefle,permapeople}', NOW()),
        ('hardiness_zones', 'union', '{trefle,permapeople}', NOW()),
        ('description', 'longest', '{trefle,permapeople}', NOW()),
        ('companion_plants', 'union', '{permapeople}', NOW()),
        ('antagonist_plants', 'union', '{permapeople}', NOW()),
        ('common_pests', 'union', '{trefle}', NOW()),
        ('bloom_season', 'priority', '{trefle}', NOW()),
        ('harvest_window', 'priority', '{trefle}', NOW()),
        ('days_to_maturity', 'priority', '{trefle}', NOW()),
        ('spacing_inches', 'priority', '{trefle}', NOW()),
        ('fertilizer_needs', 'priority', '{trefle,permapeople}', NOW())
        """
    )

    # ── Backfill perenual_plants from existing plants rows ────────────────────
    op.execute(
        """
        INSERT INTO perenual_plants (perenual_id, plant_id, common_name, scientific_name, image_url, fetched_at)
        SELECT CAST(external_id AS INTEGER), id, common_name, scientific_name, image_url, created_at
        FROM plants
        WHERE source = 'perenual' AND external_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trefle_plants')
    op.drop_table('permapeople_plants')
    op.drop_table('perenual_plants')
    op.drop_table('enrichment_rules')
    # ### end Alembic commands ###
