"""initial schema

Revision ID: 9aa156e45527
Revises: 
Create Date: 2026-02-22 07:49:09.825063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9aa156e45527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_timestamp'), 'api_request_logs', ['timestamp'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', 'skipped', name='pipeline_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('plant_type', sa.Enum('annual', 'perennial', 'shrub', 'tree', 'herb', 'vegetable', 'fruit', 'bulb', 'other', name='plant_type_enum'), nullable=True),
    sa.Column('hardiness_zones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sun_requirement', sa.Enum('full_sun', 'partial_shade', 'full_shade', name='sun_req_enum'), nullable=True),
    sa.Column('water_needs', sa.Enum('low', 'medium', 'high', name='water_needs_enum'), nullable=True),
    sa.Column('days_to_maturity', sa.Integer(), nullable=True),
    sa.Column('spacing_inches', sa.Float(), nullable=True),
    sa.Column('planting_depth_inches', sa.Float(), nullable=True),
    sa.Column('fertilizer_needs', sa.Text(), nullable=True),
    sa.Column('bloom_season', sa.String(length=100), nullable=True),
    sa.Column('harvest_window', sa.String(length=100), nullable=True),
    sa.Column('companion_plants', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('antagonist_plants', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('common_pests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('common_diseases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.Enum('perenual', 'trefle', 'usda', 'user', name='plant_source_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_user_defined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_common_name'), 'plants', ['common_name'], unique=False)
    op.create_index(op.f('ix_plants_scientific_name'), 'plants', ['scientific_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('hardiness_zone', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('high_temp_f', sa.Float(), nullable=True),
    sa.Column('low_temp_f', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('precip_inches', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(length=100), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('soil_temp_f', sa.Float(), nullable=True),
    sa.Column('frost_warning', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_date'), 'weather_cache', ['date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'export', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('gardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('square_footage', sa.Float(), nullable=True),
    sa.Column('sun_exposure', sa.Enum('full', 'partial', 'shade', name='sun_exposure_type'), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('irrigation_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gardens_user_id'), 'gardens', ['user_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('water', 'fertilize', 'frost', 'heat', 'spray', 'harvest', 'custom', name='notification_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('email', name='notification_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'failed', name='notification_status_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_preview', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_timestamp'), 'notification_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('bed_sun_exposure', sa.Enum('full', 'partial', 'shade', name='sun_exposure_type'), nullable=True),
    sa.Column('soil_amendments', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beds_garden_id'), 'beds', ['garden_id'], unique=False)
    op.create_table('plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('date_planted', sa.Date(), nullable=True),
    sa.Column('date_transplanted', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'seedling', 'growing', 'flowering', 'fruiting', 'harvesting', 'dormant', 'removed', name='planting_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantings_bed_id'), 'plantings', ['bed_id'], unique=False)
    op.create_index(op.f('ix_plantings_plant_id'), 'plantings', ['plant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_garden_id'), 'journal_entries', ['garden_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('water', 'fertilize', 'spray', 'prune', 'harvest', name='schedule_type_enum'), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('last_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_adjusted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_bed_id'), 'schedules', ['bed_id'], unique=False)
    op.create_index(op.f('ix_schedules_garden_id'), 'schedules', ['garden_id'], unique=False)
    op.create_index(op.f('ix_schedules_next_due'), 'schedules', ['next_due'], unique=False)
    op.create_index(op.f('ix_schedules_planting_id'), 'schedules', ['planting_id'], unique=False)
    op.create_table('treatment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('treatment_type', sa.Enum('herbicide', 'insecticide', 'fungicide', 'fertilizer', 'amendment', name='treatment_type_enum'), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weather_at_time', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_logs_bed_id'), 'treatment_logs', ['bed_id'], unique=False)
    op.create_index(op.f('ix_treatment_logs_planting_id'), 'treatment_logs', ['planting_id'], unique=False)
    op.create_table('watering_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_groups_garden_id'), 'watering_groups', ['garden_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watering_groups_garden_id'), table_name='watering_groups')
    op.drop_table('watering_groups')
    op.drop_index(op.f('ix_treatment_logs_planting_id'), table_name='treatment_logs')
    op.drop_index(op.f('ix_treatment_logs_bed_id'), table_name='treatment_logs')
    op.drop_table('treatment_logs')
    op.drop_index(op.f('ix_schedules_planting_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_due'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_garden_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_bed_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_garden_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_plantings_plant_id'), table_name='plantings')
    op.drop_index(op.f('ix_plantings_bed_id'), table_name='plantings')
    op.drop_table('plantings')
    op.drop_index(op.f('ix_beds_garden_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_timestamp'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_gardens_user_id'), table_name='gardens')
    op.drop_table('gardens')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_weather_cache_date'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_scientific_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_common_name'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_api_request_logs_timestamp'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
