"""add color to beds and plantings

Revision ID: c484a79139c2
Revises: 07959a398336
Create Date: 2026-03-07 02:53:24.066278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c484a79139c2'
down_revision: Union[str, None] = '07959a398336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('plantings', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantings', 'color')
    op.drop_column('beds', 'color')
    # ### end Alembic commands ###
