"""add canvas and spatial fields to garden bed planting

Revision ID: c85490249870
Revises: f4067f17fbdd
Create Date: 2026-03-06 23:24:06.772535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c85490249870'
down_revision: Union[str, None] = 'f4067f17fbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('boundary', sa.JSON(), nullable=True))
    op.add_column('gardens', sa.Column('canvas_width_ft', sa.Float(), nullable=True))
    op.add_column('gardens', sa.Column('canvas_height_ft', sa.Float(), nullable=True))
    op.add_column('plantings', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('plantings', sa.Column('pos_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantings', 'pos_y')
    op.drop_column('plantings', 'pos_x')
    op.drop_column('gardens', 'canvas_height_ft')
    op.drop_column('gardens', 'canvas_width_ft')
    op.drop_column('beds', 'boundary')
    # ### end Alembic commands ###
