"""add watering_log and schedule_id to treatment_log

Revision ID: d7b3f6a92b7d
Revises: 4bc9d9561a96
Create Date: 2026-02-25 04:44:58.935270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7b3f6a92b7d'
down_revision: Union[str, None] = '4bc9d9561a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watering_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_inches', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('drip', 'hand', 'sprinkler', 'soaker', 'other', name='watering_method_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_logs_bed_id'), 'watering_logs', ['bed_id'], unique=False)
    op.create_index(op.f('ix_watering_logs_garden_id'), 'watering_logs', ['garden_id'], unique=False)
    op.create_index(op.f('ix_watering_logs_planting_id'), 'watering_logs', ['planting_id'], unique=False)
    op.create_index(op.f('ix_watering_logs_schedule_id'), 'watering_logs', ['schedule_id'], unique=False)
    op.add_column('treatment_logs', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_treatment_logs_schedule_id'), 'treatment_logs', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'treatment_logs', 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_logs', type_='foreignkey')
    op.drop_index(op.f('ix_treatment_logs_schedule_id'), table_name='treatment_logs')
    op.drop_column('treatment_logs', 'schedule_id')
    op.drop_index(op.f('ix_watering_logs_schedule_id'), table_name='watering_logs')
    op.drop_index(op.f('ix_watering_logs_planting_id'), table_name='watering_logs')
    op.drop_index(op.f('ix_watering_logs_garden_id'), table_name='watering_logs')
    op.drop_index(op.f('ix_watering_logs_bed_id'), table_name='watering_logs')
    op.drop_table('watering_logs')
    # ### end Alembic commands ###
