"""add lat lon to gardens

Revision ID: fab1d2508a07
Revises: d7b3f6a92b7d
Create Date: 2026-02-26 04:51:31.909259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fab1d2508a07'
down_revision: Union[str, None] = 'd7b3f6a92b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('gardens', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'longitude')
    op.drop_column('gardens', 'latitude')
    # ### end Alembic commands ###
