"""add heat_warning to weather_cache

Revision ID: fd18e786a5a4
Revises: 458eba7e6de8
Create Date: 2026-03-01 16:32:44.979736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd18e786a5a4'
down_revision: Union[str, None] = '458eba7e6de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_cache', sa.Column('heat_warning', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_cache', 'heat_warning')
    # ### end Alembic commands ###
